<?php
namespace content\protocol;

use content\core\BinaryStream;

abstract class Packet extends BinaryStream {
    const NET_WORK_ID = 0;
    public $isEncoded = false;

    public function getId(){
        return $this::NET_WORK_ID;
    }

    abstract function encode();

    abstract function decode();

    public function isEncode(){
        return $this->isEncoded;
    }

    public function reset()
    {
        parent::reset(); // TODO: Change the autogenerated stub
        $this->buffer = chr($this::NET_WORK_ID);
        $this->isEncoded = false;
    }

}